
// SimOne.exe
D:\Cybertron\UnrealEngine\Output\Development\WindowsNoEditor\SimOne\Binaries\Win64


1. Rancher 
	Image: docker.51vr.local:6000/apolloauto/apollo:dev5 

2. IN Ubuntu terminal: docker ps -a
		  	docker exec -it 1c10ae5c4777  bash 
        bash scripts/bootstrap.sh
        source /apollo/scripts/apolo_base.sh
        cyber_recorder play -f docs/demo_guide/demo_3.5.record --loop

        run.sh & kill.sh


The maps located in: root@apollo5-apollo-ubuntu14-1:/Cybertron2/apollo/modules/map/data

3. The GitLab

	http://git.51vr.local/51World/apollo/tree/a3.5/docker     



6. only CyberBridge bazel build:
  root@apollo5-apollo-ubuntu14-1:/apollo# bazel build //CyberBridge:libApolloCyber.so


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Apollo官方:

1. 
   GPU version:
   sudo ./apollo.sh build_gpu  

   CPU version:
    ./apollo.sh build_cpu

   Easy version:
   bash apollo.sh build -j 8


apollo 3.5 official image:
 https://github.com/ApolloAuto/apollo/tree/r3.5.0
Apollo 3.5的构建方法:
https://blog.csdn.net/davidhopper/article/details/85097502

# Start the docker.
bash docker/scripts/dev_start.sh
# Step into the docker.
bash docker/scripts/dev_into.sh
# Build the apollo project in the docker.
# -j 8 depends on the number of CPU cores on your machine.
bash apollo.sh build -j 8

bash scripts/bootstrap.sh   
http://localhost:8888/


查看Bazel依赖图:
bazel query --nohost_deps --noimplicit_deps 'deps(//modules/dreamview:dreamview)'


2. 51VR

without perception
  apollo5-apollo-ubuntu14-1

 docker exec -it  1c10ae5c4777 bash 


root@apollo5-apollo-ubuntu14-1:/apollo# ./apollo.sh

Start the dreamview:
    bash scripts/bootstrap.sh 


3. 错误

./apollo.sh build_cpu


INFO: (07-23 01:17:44.831) Found 3742 targets...
ERROR: (07-23 01:17:46.748) /apollo/modules/perception/lidar/lib/segmentation/cnnseg/BUILD:84:1: Linking of rule '//modules/perception/lidar/lib/segmentation/cnnseg:cnn_segmentation_test' failed (Exit 1).
/usr/bin/ld: warning: libmkldnn.so.0, needed by bazel-out/local-dbg/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so, not found (try using -rpath or -rpath-link)

cd 

need to mount the volume: paddlepaddle_volume-x86_64-1.0.0




4. only CyberBridge bazel build:
  root@apollo5-apollo-ubuntu14-1:/apollo# bazel build //CyberBridge:libApolloCyber.so




5.  // How to Run Perception Module on Your Local Computer

  Build Apollo:  ./apollo.sh build_opt_gpu

  查看显卡名称以及驱动版本:  nvidia-smi


  // install nvidia-docker  // https://www.jianshu.com/p/f25ccedb996e   //https://www.dongliwu.com/archives/61/
  # If you have nvidia-docker 1.0 installed: we need to remove it and all existing GPU containers
  docker volume ls -q -f driver=nvidia-docker | xargs -r -I{} -n1 docker ps -q -a -f volume={} | xargs -r docker rm -f
  sudo apt-get purge -y nvidia-docker

  # Add the package repositories
  curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey |  sudo apt-key add -  distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
  curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list |     sudo tee /etc/apt/sources.list.d/nvidia-docker.list
  sudo apt-get update

  # Install nvidia-docker2 and reload the Docker daemon configuration
  sudo apt-get install -y nvidia-docker2
  sudo pkill -SIGHUP dockerd

  # Test nvidia-smi with the latest official CUDA image
  docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi


  // 配置daemon的默认运行时
  在安装完成nvidia-docker2之后，nvidia-docker2已经默认在/etc/docker/daemon.json文件中写入了以下内容：

  {
      "default-runtime": "nvidia",
      "runtimes": {
          "nvidia": {
              "path": "/usr/bin/nvidia-container-runtime",
              "runtimeArgs": [],
              "registry-mirrors": ["https://gemfield.mirror.aliyuncs.com"]
          }
      }
  }
  我们所做的工作其实就是在第一行加上了"default-runtime": "nvidia",


  重启docker服务: sudo systemctl restart docker

  再次检查状态: systemctl status docker









5. 
protobuffer:

zy@zy:~/Desktop/proto$ protoc addressbook.proto --cpp_out=./


6. the pb.h and pb.cc files generated by bazel are localized in the path below: 

root@apollo5-apollo-ubuntu14-1:/apollo/bazel-out/local-dbg/genfiles/modules/localization/proto# 


7. IMU publish:
  http://git.51vr.local/51World/Cybertron/blob/ue4.22/Modules/BridgeApollo/CybertronBridgeApolloCyber/TaskCyberChassisImu.cpp
  mCyberImu.publish(angvelX, angvelY, angvelZ, linAccX, linAccY, linAccZ); # 70


8. http://git.51vr.local/51World/Cybertron/blob/ue4.22/Modules/BridgeApollo/CybertronBridgeApolloCyber/TaskCyberPointCloud.cpp 

    8.1  mCyberPointCloud.publish(
            frame, 
            mPointCloud.width(),
            mPointCloud.height(),
            mPointCloud.pointstep(),
            mPointCloud.data().data()

        );                                        //CyberWriterPointCloud::publish(int sequence, int width, int height, int step, const char *data)


  8.2  CyberWriterPointCloud mCyberPointCloud;   // CyberWriterPointCloud.hpp

cybertron::proto::sensor::DataPointCloud mPointCloud; // the mPointCloud which has been published  

In cyvertron the Lidar protobuf:
cybertron::proto::sensor::DataPointCloud  //  PointCloud.pb.h
 





 

  8.4 msg.toProtobuf(mPointCloud)



   8.5
   http://git.51vr.local/51World/Cybertron/blob/master/Modules/Unreal/UnrealNodeBase/CybertronUnrealNodeBase/UnrealSensorTask.cpp_out

   void UnrealSensorTask::UpdateLaserRadarOutput(const UnrealBridge::SensorHeader& sensorHeader, int sensorId, 

                                                  const std::vector<uint8_t>& pointCloudData, 

                                                  const UnrealBridge::GroundTruthData& groundTruthData)






9. ROS   sensor_msgs/PointCloud 

        以上是标准头信息的主要部分。seq是消息的顺序标识，不需要手动设置，发布节点在发布消息时，会自动累加。stamp 是消息中与数据相关联的时间戳，例如激光数据中，时间戳对应激光数据的采集时间点。frame_id 是消息中与数据相关联的参考系id，例如在在激光数据中，frame_id对应激光数据采集的参考系

        #Standard metadata for higher-level flow data types
#sequence ID: consecutively increasing ID 
uint32 seq
 
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
 
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id





10. Apollo pointcloud.proto:

    syntax = "proto2";
    package apollo.drivers;

    import "modules/common/proto/header.proto";

    // 一帧点云
    message PointXYZIT {
      optional float x = 1 [default = nan];          //
      optional float y = 2 [default = nan];          //
      optional float z = 3 [default = nan];          //
      optional uint32 intensity = 4 [default = 0];  //激光反射强度（Intensity
      optional uint64 timestamp = 5 [default = 0];  // 每一个点的时间戳
    }

    message PointCloud {
      optional apollo.common.Header header = 1;   //
      optional string frame_id = 2;               //
      optional bool is_dense = 3;                 //
      repeated PointXYZIT point = 4;
      optional double measurement_time = 5;        //last_time_stamp_ = pointcloud->measurement_time();
      optional uint32 width = 6;                  //
      optional uint32 height = 7;                 //height与width是指点云数据的高和宽，一般无序点云的高为1，宽为点云中激光点的个数；结构化点云的高和宽均大于1。
    }




//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
11. Cybretron PointCloud.proto


syntax = "proto3";

import "Common/Header.proto";
import "Sensor/ObstacleDetect.proto";

package cybertron.proto.sensor;

enum EPointCloudFieldName
{
  EPointCloudFieldName_XYZ = 0; // float x 3
  EPointCloudFieldName_Intensity = 1; // uint16
  EPointCloudFieldName_Ring = 2; // uint16
  EPointCloudFieldName_RGB = 3; // uint8 x 3
  EPointCloudFieldName_Segmentation = 4; // uint8
  EPointCloudFieldName_InstanceId = 5; // Int32
}

// refer to http://docs.ros.org/api/sensor_msgs/html/msg/PointField.html
enum EPointCloudFieldType
{
  EPointCloudFieldType_Unused = 0;
  EPointCloudFieldType_Int8 = 1;
  EPointCloudFieldType_UInt8 = 2;
  EPointCloudFieldType_Int16 = 3;
  EPointCloudFieldType_UInt16 = 4;
  EPointCloudFieldType_Int32 = 5;
  EPointCloudFieldType_UInt32 = 6;
  EPointCloudFieldType_Float = 7;
  EPointCloudFieldType_Double = 8;
}

message PointCloudField{
  EPointCloudFieldName name = 1;      //name是指点云包含的域的名称，如“x”、“y”、“z”、“intensity”、“ring”等
  uint32 offset = 2;                  //offset是指在data的每个数据中该域的偏移量
  EPointCloudFieldType datatype = 3;  //datatype是指以上1~8的数据类型
}

message DataPointCloud {
  common.CybertronHeader header = 1;
  // 2D structure of the point cloud.
  // For unordered point cloud, height is 1 and width is point count of the point cloud.
  uint32 width = 2;
  uint32 height = 3;
  // raw data fields definition.
  repeated PointCloudField fields = 4;
  // Length of a point in bytes
  uint32 pointStep = 5;    //pointstep表示每个点的字节长度，常见的为32
  // raw data, size should be width * height * pointStep
  bytes data = 6;     //data表示所有的点的数据，以字节存储。uint8[] data代表vector类型，有size、push_back、clear等操作 //  for(unsigned int i = 0; i < num_points; ++i){
                                                                                                             //           cloud.points[i].x = 0.1*i;
                                                                                                             //           cloud.points[i].y = 0.1*i;
                                                                                                             //          cloud.points[i].z = 5;
                                                                                                             //           cloud.channels[0].values[i] = 255;
                                                                                                             //  }                                                                                                          //        }


message PointCloudStamped{
  common.Header header = 1;
  DataPointCloud pointcloud = 2;
}

message PointCloudWithGroundTruth{
  DataPointCloud pointcloud = 1;
  GroundTruth ground_truth = 2;
}


